# Generated by Django 4.1.7 on 2023-03-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_musician_alter_city_options_song_award"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="year",
            field=models.DateTimeField(),
        ),
    ]
