# Generated by Django 4.1.7 on 2023-03-08 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_award_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="nominant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="award",
                to="main.musician",
            ),
        ),
    ]
